import type { Product } from "@/lib/types";

export const products: Product[] = [
  {
    id: "1",
    name: "Half of a Yellow Sun",
    slug: "half-of-a-yellow-sun",
    description:
      "Chimamanda Ngozi Adichie's epic novel set during the Biafran War, exploring love and identity.",
    author: "Chimamanda Ngozi Adichie",
    price: 3500,
    image: "https://covers.openlibrary.org/b/id/8409783-M.jpg",
    category: "fiction",
    stock: 50,
  },
  {
    id: "2",
    name: "To Kill a Mockingbird",
    slug: "to-kill-a-mockingbird",
    description:
      "Harper Lee's classic American masterpiece exploring racial injustice and moral growth.",
    author: "Harper Lee",
    price: 2900,
    originalPrice: 3500,
    image: "https://covers.openlibrary.org/b/id/7878212-M.jpg",
    category: "fiction",
    discount: 17,
    stock: 75,
  },
  {
    id: "3",
    name: "1984",
    slug: "1984",
    description:
      "George Orwell's dystopian novel exploring totalitarianism and surveillance in modern society.",
    author: "George Orwell",
    price: 3200,
    image: "https://covers.openlibrary.org/b/id/7397984-M.jpg",
    category: "science",
    stock: 60,
  },
  {
    id: "4",
    name: "The Great Gatsby",
    slug: "the-great-gatsby",
    description:
      "F. Scott Fitzgerald's iconic tale of wealth, love, and the American Dream in the Jazz Age.",
    author: "F. Scott Fitzgerald",
    price: 2600,
    originalPrice: 3300,
    image: "https://covers.openlibrary.org/b/id/7885090-M.jpg",
    category: "fiction",
    discount: 21,
    stock: 50,
  },
  {
    id: "5",
    name: "Pride and Prejudice",
    slug: "pride-and-prejudice",
    description:
      "Jane Austen's beloved romantic novel of wit, social commentary, and true love.",
    author: "Jane Austen",
    price: 2400,
    image: "https://covers.openlibrary.org/b/id/7770118-M.jpg",
    category: "romance",
    stock: 65,
  },
  {
    id: "6",
    name: "Things Fall Apart",
    slug: "things-fall-apart",
    description:
      "Chinua Achebe's masterpiece exploring pre-colonial African society and colonialism's impact.",
    author: "Chinua Achebe",
    price: 2500,
    image: "https://covers.openlibrary.org/b/id/8413960-M.jpg",
    category: "history",
    stock: 40,
  },
  {
    id: "7",
    name: "The Catcher in the Rye",
    slug: "the-catcher-in-the-rye",
    description:
      "J.D. Salinger's novel exploring teenage alienation and identity.",
    author: "J.D. Salinger",
    price: 2800,
    originalPrice: 3400,
    image: "https://covers.openlibrary.org/b/id/7905605-M.jpg",
    category: "fiction",
    discount: 18,
    stock: 35,
  },
  {
    id: "8",
    name: "Jane Eyre",
    slug: "jane-eyre",
    description:
      "Charlotte Brontë's gothic romance following an orphaned governess seeking independence.",
    author: "Charlotte Brontë",
    price: 2700,
    image: "https://covers.openlibrary.org/b/id/7796524-M.jpg",
    category: "romance",
    stock: 45,
  },
  {
    id: "9",
    name: "Wuthering Heights",
    slug: "wuthering-heights",
    description: "Emily Brontë's passionate tale of love and revenge.",
    author: "Emily Brontë",
    price: 2500,
    originalPrice: 3100,
    image: "https://covers.openlibrary.org/b/id/8065385-M.jpg",
    category: "romance",
    discount: 19,
    stock: 50,
  },
  {
    id: "10",
    name: "Americanah",
    slug: "americanah",
    description:
      "A contemporary love story exploring race, identity, and immigration.",
    author: "Chimamanda Ngozi Adichie",
    price: 4200,
    image: "https://covers.openlibrary.org/b/id/8411854-M.jpg",
    category: "fiction",
    stock: 45,
  },
  {
    id: "11",
    name: "One Hundred Years of Solitude",
    slug: "one-hundred-years-solitude",
    description: "Magical realism and family saga across generations.",
    author: "Gabriel García Márquez",
    price: 3800,
    originalPrice: 4500,
    image: "https://covers.openlibrary.org/b/id/8410308-M.jpg",
    category: "fiction",
    discount: 15,
    stock: 35,
  },
  {
    id: "12",
    name: "Don Quixote",
    slug: "don-quixote",
    description: "An epic tale of adventure and imagination.",
    author: "Miguel de Cervantes",
    price: 3500,
    image: "https://covers.openlibrary.org/b/id/7985450-M.jpg",
    category: "classic",
    stock: 25,
  },
  {
    id: "13",
    name: "Crime and Punishment",
    slug: "crime-and-punishment",
    description: "A psychological thriller exploring guilt and redemption.",
    author: "Fyodor Dostoevsky",
    price: 4100,
    image: "https://covers.openlibrary.org/b/id/8409892-M.jpg",
    category: "psychology",
    stock: 30,
  },
  {
    id: "14",
    name: "Anna Karenina",
    slug: "anna-karenina",
    description: "A sweeping novel of love, family, and society.",
    author: "Leo Tolstoy",
    price: 4500,
    image: "https://covers.openlibrary.org/b/id/8415097-M.jpg",
    category: "classic",
    stock: 28,
  },
  {
    id: "15",
    name: "The Famished Road",
    slug: "the-famished-road",
    description:
      "A spirit-child's journey through Nigeria blending myth and reality.",
    author: "Ben Okri",
    price: 3800,
    originalPrice: 4500,
    image: "https://covers.openlibrary.org/b/id/8412756-M.jpg",
    category: "fiction",
    discount: 15,
    stock: 30,
  },
  {
    id: "16",
    name: "Beloved",
    slug: "beloved",
    description: "A powerful novel exploring memory, trauma, and identity.",
    author: "Toni Morrison",
    price: 3900,
    image: "https://covers.openlibrary.org/b/id/8409045-M.jpg",
    category: "history",
    stock: 40,
  },
  {
    id: "17",
    name: "Purple Hibiscus",
    slug: "purple-hibiscus",
    description: "A coming-of-age novel about family and faith.",
    author: "Chimamanda Ngozi Adichie",
    price: 3400,
    image: "https://covers.openlibrary.org/b/id/8228691-M.jpg",
    category: "fiction",
    stock: 42,
  },
  {
    id: "18",
    name: "The Alchemist",
    slug: "the-alchemist",
    description: "A philosophical journey about destiny and dreams.",
    author: "Paulo Coelho",
    price: 3000,
    originalPrice: 3600,
    image: "https://covers.openlibrary.org/b/id/8101356-M.jpg",
    category: "self-help",
    discount: 16,
    stock: 55,
  },
  {
    id: "19",
    name: "The Kite Runner",
    slug: "the-kite-runner",
    description: "A powerful story of friendship and redemption.",
    author: "Khaled Hosseini",
    price: 3700,
    image: "https://covers.openlibrary.org/b/id/8231856-M.jpg",
    category: "fiction",
    stock: 38,
  },
  {
    id: "20",
    name: "The Book Thief",
    slug: "the-book-thief",
    description: "A historical novel set in Nazi Germany narrated by Death.",
    author: "Markus Zusak",
    price: 3600,
    originalPrice: 4200,
    image: "https://covers.openlibrary.org/b/id/8231996-M.jpg",
    category: "history",
    discount: 14,
    stock: 47,
  },
];
